"""
India AI Grid
Surface Water Assessment Model

File:
    backend/models/site_assessment/water/surface_water.py

Purpose:
    Analyze surface-water sources around a proposed data-center
    location.

Supported source types:
    - River
    - Reservoir
    - Lake
    - Canal
    - Water body
    - Stream

This module evaluates:

    1. Distance from proposed site
    2. Source type
    3. Observation recency
    4. Storage information
    5. Flow information
    6. Data completeness
    7. Spatial confidence
    8. Reliability indicators

IMPORTANT
---------
A nearby river/reservoir/lake does NOT automatically mean that
water is available for a data center.

Actual industrial water availability depends on:

    - legal permissions
    - water allocation
    - environmental requirements
    - sustainable withdrawal
    - infrastructure
    - treatment requirements
    - seasonal availability
    - local authority rules

Therefore this model intentionally does NOT return:

    "water_available = true"

based only on geographic proximity.

Final site suitability will be calculated later by:

    seasonal_reliability.py
    treatment.py
    water_score.py
"""


from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import date, datetime, timezone
from math import atan2, cos, radians, sin, sqrt
from typing import Any, Dict, List, Optional


# ============================================================
# TYPE ALIASES
# ============================================================

Number = Optional[float]


# ============================================================
# DATA MODEL
# ============================================================


@dataclass
class SurfaceWaterSource:
    """
    Normalized surface-water observation.

    This is the object that should eventually be produced by
    the CWC / India-WRIS / state-water-data adapters.
    """

    source_id: Optional[str] = None

    name: Optional[str] = None

    source_type: Optional[str] = None

    latitude: Number = None

    longitude: Number = None

    state: Optional[str] = None

    district: Optional[str] = None

    observation_date: Optional[str] = None

    water_level_m: Number = None

    storage_mcm: Number = None

    capacity_mcm: Number = None

    flow_cumecs: Number = None

    source: Optional[str] = None


@dataclass
class SurfaceWaterAssessment:
    """
    Result generated by SurfaceWaterModel.
    """

    available: bool

    source_id: Optional[str]

    name: Optional[str]

    source_type: Optional[str]

    distance_km: Number

    spatial_confidence: str

    observation_recency: str

    storage_status: str

    flow_status: str

    data_completeness: str

    reliability_indicator: str

    legal_availability: str

    concerns: List[str]

    warnings: List[str]

    summary: str


# ============================================================
# THRESHOLDS
# ============================================================


class SurfaceWaterThresholds:
    """
    Screening thresholds.

    These values are NOT legal limits and are NOT final
    engineering design requirements.

    They are used only for preliminary site assessment.
    """

    # Distance from site

    VERY_NEAR_KM: float = 5.0

    NEAR_KM: float = 15.0

    MODERATE_KM: float = 30.0

    FAR_KM: float = 60.0

    # Observation age

    RECENT_DAYS: int = 365

    AGING_DAYS: int = 3 * 365

    OLD_DAYS: int = 5 * 365

    # Storage ratio

    HIGH_STORAGE_RATIO: float = 0.70

    MODERATE_STORAGE_RATIO: float = 0.40

    LOW_STORAGE_RATIO: float = 0.20


# ============================================================
# SURFACE WATER MODEL
# ============================================================


class SurfaceWaterModel:
    """
    Surface-water assessment engine.
    """

    def __init__(
        self,
        thresholds: Optional[SurfaceWaterThresholds] = None,
    ) -> None:

        self.thresholds = (
            thresholds
            if thresholds is not None
            else SurfaceWaterThresholds()
        )

    # ========================================================
    # VALIDATION
    # ========================================================

    @staticmethod
    def valid_latitude(
        latitude: Optional[float],
    ) -> bool:

        if latitude is None:
            return False

        return -90.0 <= latitude <= 90.0

    @staticmethod
    def valid_longitude(
        longitude: Optional[float],
    ) -> bool:

        if longitude is None:
            return False

        return -180.0 <= longitude <= 180.0

    # ========================================================
    # DISTANCE
    # ========================================================

    @staticmethod
    def haversine_distance_km(
        latitude_1: float,
        longitude_1: float,
        latitude_2: float,
        longitude_2: float,
    ) -> float:
        """
        Calculate great-circle distance between two coordinates.

        Returns:
            Distance in kilometres.
        """

        if not SurfaceWaterModel.valid_latitude(latitude_1):
            raise ValueError(
                "latitude_1 must be between -90 and 90."
            )

        if not SurfaceWaterModel.valid_latitude(latitude_2):
            raise ValueError(
                "latitude_2 must be between -90 and 90."
            )

        if not SurfaceWaterModel.valid_longitude(longitude_1):
            raise ValueError(
                "longitude_1 must be between -180 and 180."
            )

        if not SurfaceWaterModel.valid_longitude(longitude_2):
            raise ValueError(
                "longitude_2 must be between -180 and 180."
            )

        earth_radius_km: float = 6371.0088

        lat_1 = radians(latitude_1)
        lat_2 = radians(latitude_2)

        delta_lat = radians(
            latitude_2 - latitude_1
        )

        delta_lon = radians(
            longitude_2 - longitude_1
        )

        a: float = (
            sin(delta_lat / 2.0) ** 2
            + (
                cos(lat_1)
                * cos(lat_2)
                * sin(delta_lon / 2.0) ** 2
            )
        )

        c: float = 2.0 * atan2(
            sqrt(a),
            sqrt(1.0 - a),
        )

        return earth_radius_km * c

    # ========================================================
    # SPATIAL CONFIDENCE
    # ========================================================

    def spatial_confidence(
        self,
        distance_km: Number,
    ) -> str:
        """
        Determine confidence based on distance between the
        proposed site and the surface-water observation.

        This is NOT a water-availability score.
        """

        if distance_km is None:
            return "unknown"

        if distance_km < 0:
            return "invalid"

        if (
            distance_km
            <= self.thresholds.VERY_NEAR_KM
        ):
            return "very_high"

        if (
            distance_km
            <= self.thresholds.NEAR_KM
        ):
            return "high"

        if (
            distance_km
            <= self.thresholds.MODERATE_KM
        ):
            return "medium"

        if (
            distance_km
            <= self.thresholds.FAR_KM
        ):
            return "low"

        return "very_low"

    # ========================================================
    # SOURCE TYPE
    # ========================================================

    @staticmethod
    def normalize_source_type(
        source_type: Optional[str],
    ) -> str:
        """
        Normalize source-type names from different APIs.
        """

        if not source_type:
            return "unknown"

        value: str = (
            source_type
            .strip()
            .lower()
            .replace("-", " ")
            .replace("_", " ")
        )

        mapping: Dict[str, str] = {

            "river": "river",

            "stream": "river",

            "river stream": "river",

            "reservoir": "reservoir",

            "dam": "reservoir",

            "dam reservoir": "reservoir",

            "lake": "lake",

            "canal": "canal",

            "waterbody": "water_body",

            "water body": "water_body",

            "pond": "water_body",

            "tank": "water_body",
        }

        return mapping.get(
            value,
            value,
        )

    # ========================================================
    # DATE PARSING
    # ========================================================

    @staticmethod
    def parse_date(
        value: Optional[str],
    ) -> Optional[date]:
        """
        Parse common date formats returned by Indian
        government datasets.
        """

        if not value:
            return None

        clean_value: str = str(value).strip()

        formats: List[str] = [

            "%Y-%m-%d",

            "%d-%m-%Y",

            "%d/%m/%Y",

            "%Y/%m/%d",

            "%d-%b-%Y",

            "%d %b %Y",

            "%Y-%m-%dT%H:%M:%S",

        ]

        for date_format in formats:

            try:

                return datetime.strptime(
                    clean_value,
                    date_format,
                ).date()

            except ValueError:

                continue

        # ISO 8601 fallback

        try:

            return datetime.fromisoformat(
                clean_value.replace(
                    "Z",
                    "+00:00",
                )
            ).date()

        except ValueError:

            return None

    # ========================================================
    # OBSERVATION RECENCY
    # ========================================================

    def observation_recency(
        self,
        observation_date: Optional[str],
        reference_date: Optional[date] = None,
    ) -> str:
        """
        Categorize how recent the observation is.
        """

        parsed_date: Optional[date] = (
            self.parse_date(
                observation_date
            )
        )

        if parsed_date is None:
            return "unknown"

        if reference_date is None:

            reference_date = (
                datetime.now(
                    timezone.utc
                ).date()
            )

        age_days: int = (
            reference_date
            - parsed_date
        ).days

        if age_days < 0:
            return "invalid_future_date"

        if (
            age_days
            <= self.thresholds.RECENT_DAYS
        ):
            return "recent"

        if (
            age_days
            <= self.thresholds.AGING_DAYS
        ):
            return "aging"

        if (
            age_days
            <= self.thresholds.OLD_DAYS
        ):
            return "old"

        return "very_old"

    # ========================================================
    # STORAGE
    # ========================================================

    def storage_status(
        self,
        storage_mcm: Number,
        capacity_mcm: Number,
    ) -> str:
        """
        Classify reservoir/lake storage.

        If capacity is available, storage is evaluated as
        a percentage of total capacity.
        """

        if storage_mcm is None:
            return "unknown"

        if storage_mcm < 0:
            return "invalid"

        if (
            capacity_mcm is not None
            and capacity_mcm > 0
        ):

            storage_ratio: float = (
                storage_mcm
                / capacity_mcm
            )

            if (
                storage_ratio
                >= self.thresholds.HIGH_STORAGE_RATIO
            ):
                return "high"

            if (
                storage_ratio
                >= self.thresholds.MODERATE_STORAGE_RATIO
            ):
                return "moderate"

            if (
                storage_ratio
                >= self.thresholds.LOW_STORAGE_RATIO
            ):
                return "low"

            return "very_low"

        # No capacity available.

        if storage_mcm == 0:
            return "empty_or_zero"

        if storage_mcm >= 1000:
            return "large"

        if storage_mcm >= 100:
            return "moderate"

        return "small"

    # ========================================================
    # FLOW
    # ========================================================

    @staticmethod
    def flow_status(
        flow_cumecs: Number,
    ) -> str:
        """
        Classify observed flow.

        These categories are only screening categories.
        They do not represent guaranteed annual water supply.
        """

        if flow_cumecs is None:
            return "unknown"

        if flow_cumecs < 0:
            return "invalid"

        if flow_cumecs == 0:
            return "zero_or_no_flow"

        if flow_cumecs < 1.0:
            return "very_low"

        if flow_cumecs < 10.0:
            return "low"

        if flow_cumecs < 100.0:
            return "moderate"

        if flow_cumecs < 1000.0:
            return "high"

        return "very_high"

    # ========================================================
    # WATER LEVEL
    # ========================================================

    @staticmethod
    def water_level_status(
        water_level_m: Number,
    ) -> str:
        """
        Basic classification of reported water level.

        No universal suitability conclusion is made here because
        water-level meaning differs between rivers, reservoirs,
        lakes and monitoring stations.
        """

        if water_level_m is None:
            return "unknown"

        if water_level_m < 0:
            return "invalid"

        return "available"

    # ========================================================
    # DATA COMPLETENESS
    # ========================================================

    @staticmethod
    def data_completeness(
        source: SurfaceWaterSource,
    ) -> str:
        """
        Calculate completeness of core source metadata.
        """

        required_fields: List[bool] = [

            source.source_id is not None,

            source.name is not None,

            source.source_type is not None,

            source.latitude is not None,

            source.longitude is not None,

            source.observation_date is not None,

        ]

        available_count: int = sum(
            1
            for field_available in required_fields
            if field_available
        )

        total_fields: int = len(
            required_fields
        )

        ratio: float = (
            available_count
            / total_fields
        )

        if ratio == 1.0:
            return "high"

        if ratio >= 0.75:
            return "medium"

        if ratio > 0.0:
            return "low"

        return "unavailable"

    # ========================================================
    # RELIABILITY INDICATOR
    # ========================================================

    @staticmethod
    def reliability_indicator(
        source_type: str,
        storage_status: str,
        flow_status: str,
        observation_recency: str,
    ) -> str:
        """
        Produce an evidence-strength indicator.

        This is NOT a final water-availability score.
        """

        evidence_points: int = 0

        if observation_recency == "recent":
            evidence_points += 1

        # Storage is particularly useful for reservoirs/lakes.

        if storage_status in {
            "high",
            "large",
        }:

            evidence_points += 2

        elif storage_status in {
            "moderate",
        }:

            evidence_points += 1

        # Flow is particularly useful for rivers.

        if flow_status in {
            "moderate",
            "high",
            "very_high",
        }:

            evidence_points += 2

        elif flow_status == "low":

            evidence_points += 1

        # Source-specific evidence.

        if source_type == "river":

            if flow_status != "unknown":
                evidence_points += 1

        elif source_type == "reservoir":

            if storage_status != "unknown":
                evidence_points += 1

        elif source_type == "lake":

            if storage_status != "unknown":
                evidence_points += 1

        if evidence_points >= 5:
            return "strong_indicator"

        if evidence_points >= 3:
            return "moderate_indicator"

        if evidence_points >= 1:
            return "weak_indicator"

        return "insufficient_data"

    # ========================================================
    # MAIN SOURCE ANALYSIS
    # ========================================================

    def analyze_source(
        self,
        source: SurfaceWaterSource,
        site_latitude: Optional[float],
        site_longitude: Optional[float],
    ) -> SurfaceWaterAssessment:
        """
        Analyze one surface-water source.
        """

        # ----------------------------------------------------
        # Coordinate validation
        # ----------------------------------------------------

        if (
            site_latitude is None
            or site_longitude is None
        ):

            distance_km: Number = None

        elif (
            source.latitude is None
            or source.longitude is None
        ):

            distance_km = None

        elif not self.valid_site_coordinates(
            site_latitude,
            site_longitude,
        ):

            raise ValueError(
                "Invalid site coordinates."
            )

        elif not self.valid_source_coordinates(
            source.latitude,
            source.longitude,
        ):

            distance_km = None

        else:

            distance_km = (
                self.haversine_distance_km(
                    site_latitude,
                    site_longitude,
                    source.latitude,
                    source.longitude,
                )
            )

        # ----------------------------------------------------
        # Normalize source type
        # ----------------------------------------------------

        normalized_source_type: str = (
            self.normalize_source_type(
                source.source_type
            )
        )

        # ----------------------------------------------------
        # Observation recency
        # ----------------------------------------------------

        recency: str = (
            self.observation_recency(
                source.observation_date
            )
        )

        # ----------------------------------------------------
        # Storage
        # ----------------------------------------------------

        storage: str = (
            self.storage_status(
                source.storage_mcm,
                source.capacity_mcm,
            )
        )

        # ----------------------------------------------------
        # Flow
        # ----------------------------------------------------

        flow: str = (
            self.flow_status(
                source.flow_cumecs
            )
        )

        # ----------------------------------------------------
        # Spatial confidence
        # ----------------------------------------------------

        spatial_confidence: str = (
            self.spatial_confidence(
                distance_km
            )
        )

        # ----------------------------------------------------
        # Data completeness
        # ----------------------------------------------------

        completeness: str = (
            self.data_completeness(
                source
            )
        )

        # ----------------------------------------------------
        # Reliability
        # ----------------------------------------------------

        reliability: str = (
            self.reliability_indicator(
                source_type=normalized_source_type,
                storage_status=storage,
                flow_status=flow,
                observation_recency=recency,
            )
        )

        # ----------------------------------------------------
        # Concerns / warnings
        # ----------------------------------------------------

        concerns: List[str] = []

        warnings: List[str] = []

        # Distance

        if spatial_confidence in {
            "low",
            "very_low",
        }:

            warnings.append(
                "Surface-water source is relatively "
                "far from the proposed site."
            )

        # Recency

        if recency in {
            "old",
            "very_old",
        }:

            warnings.append(
                "Surface-water observation is old; "
                "current conditions may differ."
            )

        elif recency == "unknown":

            warnings.append(
                "Observation date is unavailable."
            )

        # Storage

        if storage in {
            "low",
            "very_low",
            "empty_or_zero",
        }:

            concerns.append(
                "low_surface_water_storage"
            )

        # Flow

        if flow in {
            "zero_or_no_flow",
            "very_low",
        }:

            concerns.append(
                "low_surface_water_flow"
            )

        # Completeness

        if completeness in {
            "low",
            "unavailable",
        }:

            warnings.append(
                "Surface-water metadata is incomplete."
            )

        # Legal access

        warnings.append(
            "Geographic proximity does not establish "
            "legal or contractual access to water."
        )

        warnings.append(
            "Industrial withdrawal, allocation, "
            "environmental-flow requirements and "
            "local permissions must be verified."
        )

        # ----------------------------------------------------
        # Summary
        # ----------------------------------------------------

        summary: str = (
            self.generate_summary(
                source_type=normalized_source_type,
                distance_km=distance_km,
                storage_status=storage,
                flow_status=flow,
                observation_recency=recency,
                reliability=reliability,
            )
        )

        return SurfaceWaterAssessment(

            available=True,

            source_id=source.source_id,

            name=source.name,

            source_type=normalized_source_type,

            distance_km=distance_km,

            spatial_confidence=spatial_confidence,

            observation_recency=recency,

            storage_status=storage,

            flow_status=flow,

            data_completeness=completeness,

            reliability_indicator=reliability,

            legal_availability="requires_verification",

            concerns=concerns,

            warnings=warnings,

            summary=summary,
        )

    # ========================================================
    # MULTIPLE SOURCE ANALYSIS
    # ========================================================

    def analyze_sources(
        self,
        sources: List[SurfaceWaterSource],
        site_latitude: float,
        site_longitude: float,
    ) -> List[SurfaceWaterAssessment]:
        """
        Analyze multiple surface-water sources and return
        them ordered by distance.
        """

        assessments: List[
            SurfaceWaterAssessment
        ] = []

        for source in sources:

            assessment: SurfaceWaterAssessment = (
                self.analyze_source(
                    source=source,
                    site_latitude=site_latitude,
                    site_longitude=site_longitude,
                )
            )

            assessments.append(
                assessment
            )

        assessments.sort(
            key=self.distance_sort_key
        )

        return assessments

    # ========================================================
    # SORTING
    # ========================================================

    @staticmethod
    def distance_sort_key(
        assessment: SurfaceWaterAssessment,
    ) -> float:
        """
        Sorting key for nearest-source analysis.
        """

        if assessment.distance_km is None:
            return float("inf")

        return assessment.distance_km

    # ========================================================
    # NEAREST SOURCE
    # ========================================================

    def nearest_source(
        self,
        sources: List[SurfaceWaterSource],
        site_latitude: float,
        site_longitude: float,
    ) -> Optional[SurfaceWaterAssessment]:
        """
        Return the physically nearest known source.
        """

        assessments: List[
            SurfaceWaterAssessment
        ] = self.analyze_sources(
            sources=sources,
            site_latitude=site_latitude,
            site_longitude=site_longitude,
        )

        if not assessments:
            return None

        return assessments[0]

    # ========================================================
    # COORDINATE HELPERS
    # ========================================================

    @staticmethod
    def valid_site_coordinates(
        latitude: float,
        longitude: float,
    ) -> bool:

        return (
            SurfaceWaterModel.valid_latitude(
                latitude
            )
            and
            SurfaceWaterModel.valid_longitude(
                longitude
            )
        )

    @staticmethod
    def valid_source_coordinates(
        latitude: float,
        longitude: float,
    ) -> bool:

        return (
            SurfaceWaterModel.valid_latitude(
                latitude
            )
            and
            SurfaceWaterModel.valid_longitude(
                longitude
            )
        )

    # ========================================================
    # SUMMARY
    # ========================================================

    @staticmethod
    def generate_summary(
        source_type: str,
        distance_km: Number,
        storage_status: str,
        flow_status: str,
        observation_recency: str,
        reliability: str,
    ) -> str:
        """
        Generate human-readable assessment summary.
        """

        if distance_km is None:

            distance_text: str = (
                "unknown distance"
            )

        else:

            distance_text = (
                f"{distance_km:.2f} km"
            )

        return (
            f"Surface-water source type is "
            f"'{source_type}' and is approximately "
            f"{distance_text} from the proposed site. "
            f"Storage status is '{storage_status}', "
            f"flow status is '{flow_status}', and "
            f"observation recency is "
            f"'{observation_recency}'. "
            f"The available evidence provides a "
            f"'{reliability}' reliability indicator. "
            f"Legal, sustainable and operational water "
            f"access requires separate verification."
        )


# ============================================================
# PUBLIC API
# ============================================================


def analyze_surface_water(
    source: SurfaceWaterSource,
    site_latitude: float,
    site_longitude: float,
) -> Dict[str, Any]:
    """
    Convenience function for API/service layers.
    """

    model: SurfaceWaterModel = (
        SurfaceWaterModel()
    )

    result: SurfaceWaterAssessment = (
        model.analyze_source(
            source=source,
            site_latitude=site_latitude,
            site_longitude=site_longitude,
        )
    )

    return asdict(result)


# ============================================================
# TEST / DEVELOPMENT
# ============================================================


if __name__ == "__main__":

    import json

    sample_source: SurfaceWaterSource = (
        SurfaceWaterSource(

            source_id="CWC-TEST-001",

            name="Example Reservoir",

            source_type="reservoir",

            latitude=20.0050,

            longitude=73.7850,

            state="Maharashtra",

            district="Nashik",

            observation_date="2026-06-15",

            water_level_m=18.2,

            storage_mcm=850.0,

            capacity_mcm=1200.0,

            flow_cumecs=None,

            source="CWC",
        )
    )

    model: SurfaceWaterModel = (
        SurfaceWaterModel()
    )

    result: SurfaceWaterAssessment = (
        model.analyze_source(

            source=sample_source,

            site_latitude=20.0120,

            site_longitude=73.7900,
        )
    )

    print(
        json.dumps(
            asdict(result),
            indent=2,
            ensure_ascii=False,
        )
    )